# Generated by Django 3.1.3 on 2022-03-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petstagramuser',
            name='date_joined',
        ),
    ]
